[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${U}",
    "${USDT}",
]

collateral = [
    "${ptsUSDe09APR2026Plasma}",
    "${ptsUSDe09APR2026Plasma}",
]

oracle = [
  "${ptsUSDe09APR2026PlasmaUBroker}",
  "${ptsUSDe09APR2026PlasmaUSDTBroker}",
]

irm = [
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
]

[bsc.uint]
lltv = [
    "${LLTV_945}",
    "${LLTV_945}",
]
