[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${USDT}",
    "${USD1}",
    "${U}",
    "${USDT}",
    "${USD1}",
    "${U}",
    "${WBNB}",
]

collateral = [
    "${USDC_USDT}",
    "${USDC_USDT}",
    "${USDC_USDT}",
    "${slisBNB_BNB}",
    "${slisBNB_BNB}",
    "${slisBNB_BNB}",
    "${slisBNB_BNB}",
]

oracle = [
    "${USDC_USDT_USDTBroker}",
    "${USDC_USDT_USD1Broker}",
    "${USDC_USDT_UBroker}",
    "${slisBNB_BNB_USDTBroker}",
    "${slisBNB_BNB_USD1Broker}",
    "${slisBNB_BNB_UBroker}",
    "${slisBNB_BNB_WBNBBroker}",
]

irm = [
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
]

[bsc.uint]
lltv = [
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_965}",
    "${LLTV_86}",
    "${LLTV_86}",
    "${LLTV_86}",
    "${LLTV_965}",
]
