[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
  "${USD1}",
  "${USD1}",
  "${U}",
  "${U}",
  "${USDT}",
  "${USDT}",
]

collateral = [
  "${BTCB}",
  "${slisBNB}",
  "${BTCB}",
  "${slisBNB}",
  "${BTCB}",
  "${slisBNB}",
]

oracle = [
  "${BTCBUSD1Broker}",
  "${slisBNBUSD1Broker}",
  "${BTCBUBroker}",
  "${slisBNBUBroker}",
  "${BTCBUSDTBroker}",
  "${slisBNBUSDTBroker}",
]

irm = [
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
    "${ALPHA_IRM}",
]

[bsc.uint]
lltv = [
    "${LLTV_86}",
    "${LLTV_86}",
    "${LLTV_86}",
    "${LLTV_86}",
    "${LLTV_86}",
    "${LLTV_86}",
]
