[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
loan = [
    "${WBNB}",
]

collateral = [
    "${slisBNB}",
]

oracle = [
  "${slisBNBWBNBBroker}",
]

irm = [
    "${ALPHA_IRM}",
]

[bsc.uint]
lltv = [
    "${LLTV_965}",
]
