[bsc]
enendpoint_url = "${BSC_RPC_URL}"

[bsc.address]
ptCollateral = [
  "${ptSUSDai15OTC2026}",
  "${ptSUSDai15OTC2026}",
  "${ptSUSDai15OTC2026}",
  "${ptCUSD24JUL2026}",
  "${ptCUSD24JUL2026}",
  "${ptCUSD24JUL2026}",
]
ptLoan = [
  "${U}",
  "${USD1}",
  "${USDT}",
  "${U}",
  "${USD1}",
  "${USDT}",
]
ptOracle = [
  "${ptSUSDai15OTC2026BaseOracle}",
  "${ptSUSDai15OTC2026BaseOracle}",
  "${ptSUSDai15OTC2026BaseOracle}",
  "${ptCUSD24JUL2026BaseOracle}",
  "${ptCUSD24JUL2026BaseOracle}",
  "${ptCUSD24JUL2026BaseOracle}",
]
multiOracle = "${MULTI_ORACLE}"
admin = "${ADMIN}"

[bsc.string]
ptMarketOracle = "0xf9135dCC8c520331c73e8538BC22e409Af8BA265"
